spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:integration}"
    username: ${DB_USER:integration}
    password: ${DB_PASS:integration}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false