CREATE SEQUENCE INT_MESSAGE_SEQ START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE TABLE INT_CHANNEL_MESSAGE (
    MESSAGE_ID       CHAR(36)     NOT NULL,
    GROUP_KEY        CHAR(36)     NOT NULL,
    CREATED_DATE     BIGINT       NOT NULL,
    MESSAGE_PRIORITY BIGINT,
    MESSAGE_SEQUENCE BIGINT       NOT NULL DEFAULT nextval('INT_MESSAGE_SEQ'),
    MESSAGE_BYTES    BYTEA,
    REGION           VARCHAR(100) NOT NULL,
    constraint INT_CHANNEL_MESSAGE_PK primary key (REGION, GROUP_KEY, CREATED_DATE, MESSAGE_SEQUENCE)
);

CREATE FUNCTION INT_CHANNEL_MESSAGE_NOTIFY_FCT()
    RETURNS TRIGGER AS
    $BODY$
        BEGIN
            PERFORM pg_notify('int_channel_message_notify', NEW.REGION || ' ' || NEW.GROUP_KEY);
            RETURN NEW;
        END;
	$BODY$
LANGUAGE PLPGSQL;

CREATE TRIGGER INT_CHANNEL_MESSAGE_NOTIFY_TRG
    AFTER INSERT
    ON INT_CHANNEL_MESSAGE
    FOR EACH ROW
    EXECUTE PROCEDURE INT_CHANNEL_MESSAGE_NOTIFY_FCT();